### ISSUE TITLE
Design and Features 

### ISSUE THREAD

**Issue by beamingboy** [beamingboy/portfolio#1]
### Design

- [ ] Design UI using the FIGMA
- [ ] Do Some Research

### Features

- [ ] Switch the theme
- [ ] Responsive
- [ ] Contact Form
- [ ] Scrool effects
